# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x05unary\"+\n\x0fInventoryRecord\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08recieved\x18\x02 \x01(\x08\x32I\n\nSearchByID\x12;\n\x11GetServerResponse\x12\x0e.unary.Message\x1a\x16.unary.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYRECORD']._serialized_start=26
  _globals['_INVENTORYRECORD']._serialized_end=69
  _globals['_MESSAGE']._serialized_start=71
  _globals['_MESSAGE']._serialized_end=97
  _globals['_MESSAGERESPONSE']._serialized_start=99
  _globals['_MESSAGERESPONSE']._serialized_end=151
  _globals['_SEARCHBYID']._serialized_start=153
  _globals['_SEARCHBYID']._serialized_end=226
# @@protoc_insertion_point(module_scope)
